version: '2.1'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lobsters
      - POSTGRES_USER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - 'lobsters_database:/var/lib/postgresql'
  app:
    image: autolobsters/lobsters:latest
    build:
      context: .
      args:
        DEVELOPER_BUILD: "false"
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME=FLOBSTERS
      - RAILS_ENV=production
      - LOBSTER_HOSTNAME=localhost
      - VIRTUAL_HOST=localhost
      - RAILS_MAX_THREADS=5
      - OPEN_SIGNUPS=true
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  lobsters_database:
    driver: local