version: '2.1'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      timeout: 5s
      retries: 20
    volumes:
      - 'lobsters_database:/var/lib/mysql'
  app:
    image: autolobsters/lobsters:latest
    build:
      context: .
      args:
        DEVELOPER_BUILD: "false"
    environment:
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_PASSWORD=password
      - MARIADB_USER=root
      - LOBSTER_DATABASE=lobsters
      - LOBSTER_SITE_NAME=FLOBSTERS
      - RAILS_ENV=development
      - LOBSTER_HOSTNAME=localhost
      - VIRTUAL_HOST=localhost
      - RAILS_MAX_THREADS=5
      - OPEN_SIGNUPS=true
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  lobsters_database:
    driver: local